// ============================================================
// Therapy Prep Report Service
// File: src/services/therapyReportService.js
//
// Generates weekly/monthly reports for family therapists.
// Review Finding #5: Granular per-channel consent, family preview,
// legal disclaimer, consent audit trail.
//
// Reports include ONLY data from consented channels.
// ============================================================

const crypto = require('crypto');
const { Pool } = require('pg');
const Sentry = require('../instrument');

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const LEGAL_DISCLAIMER = `This report is generated by AI analysis of communication patterns and is intended for therapeutic context only. It is not a clinical assessment and should not be used in legal proceedings. Generated by ASCEN BreathWorx Guided Bridge.`;
const LEGAL_DISCLAIMER_VERSION = 1;

// ── GENERATE REPORT ─────────────────────────────────────────

async function generateReport(familyUnitId, periodStart, periodEnd, consentChannels, tenantId) {
  const aiRouter = require('./aiRouter');

  try {
    // Validate consent exists for each channel
    const channels = consentChannels || {};
    const consentedChannels = Object.entries(channels)
      .filter(([_, consented]) => consented)
      .map(([channel]) => channel);

    if (consentedChannels.length === 0) {
      return { error: true, message: 'At least one channel must be consented for report generation' };
    }

    // Gather data ONLY from consented channels
    const reportData = {};

    // Communication volume
    const volumeResult = await pool.query(
      `SELECT channel_type, COUNT(*) as message_count,
              AVG(EXTRACT(EPOCH FROM (delivered_at - sent_at))) as avg_response_seconds,
              COUNT(DISTINCT sender_id) as unique_senders
       FROM facilitated_messages
       WHERE family_unit_id = $1 AND channel_type = ANY($2)
         AND created_at BETWEEN $3 AND $4
         AND delivered_at IS NOT NULL
       GROUP BY channel_type`,
      [familyUnitId, consentedChannels, periodStart, periodEnd]
    );
    reportData.communication_volume = volumeResult.rows;

    // Engagement patterns
    const engagementResult = await pool.query(
      `SELECT
         COUNT(*) as total_messages,
         COUNT(*) FILTER (WHERE read_at IS NOT NULL) as read_messages,
         COUNT(*) FILTER (WHERE sender_accepted_coaching = true) as coaching_accepted,
         COUNT(*) FILTER (WHERE sender_accepted_coaching = false) as coaching_rejected,
         COUNT(*) FILTER (WHERE facilitator_decision = 'coach') as coached_messages
       FROM facilitated_messages
       WHERE family_unit_id = $1 AND channel_type = ANY($2)
         AND created_at BETWEEN $3 AND $4`,
      [familyUnitId, consentedChannels, periodStart, periodEnd]
    );
    reportData.engagement = engagementResult.rows[0] || {};

    // Conflict log
    const conflictResult = await pool.query(
      `SELECT channel_type, escalation_score, resolution_outcome,
              breathing_session_completed, clinical_flag, created_at
       FROM conflict_events
       WHERE family_unit_id = $1 AND channel_type = ANY($2)
         AND created_at BETWEEN $3 AND $4
       ORDER BY created_at`,
      [familyUnitId, consentedChannels, periodStart, periodEnd]
    );
    reportData.conflict_log = conflictResult.rows;

    // Shared session data (co-breath)
    const coBreathResult = await pool.query(
      `SELECT COUNT(*) as session_count,
              AVG(connection_score) as avg_connection_score,
              COUNT(*) FILTER (WHERE mutual_regulation_success) as mutual_regulation_count
       FROM cobreath_sessions
       WHERE family_unit_id = $1
         AND created_at BETWEEN $2 AND $3
         AND status = 'completed'`,
      [familyUnitId, periodStart, periodEnd]
    );
    reportData.shared_sessions = coBreathResult.rows[0] || {};

    // Generate Sonnet analysis
    const analysisPrompt = `
      Analyze this family therapy prep report data for the period ${periodStart} to ${periodEnd}.

      Communication Volume: ${JSON.stringify(reportData.communication_volume)}
      Engagement: ${JSON.stringify(reportData.engagement)}
      Conflict Events: ${JSON.stringify(reportData.conflict_log)}
      Shared Sessions: ${JSON.stringify(reportData.shared_sessions)}

      Provide analysis as JSON:
      {
        "positive_signals": ["list of positive patterns observed"],
        "areas_of_concern": ["list of concerning patterns"],
        "recommendations": ["actionable recommendations for therapist"],
        "progress_summary": "2-3 sentence summary of overall family progress"
      }
    `;

    const analysisResult = await aiRouter.route('therapy_report', analysisPrompt, {
      maxTokens: 1000,
      temperature: 0.3,
      tenantId
    });

    let analysis;
    try {
      analysis = JSON.parse(analysisResult?.content || '{}');
    } catch {
      analysis = {
        positive_signals: ['AI analysis unavailable'],
        areas_of_concern: [],
        recommendations: ['Manual review recommended'],
        progress_summary: 'AI analysis was unavailable for this report period.'
      };
    }

    reportData.analysis = analysis;

    // Compute report hash for audit verification
    const reportContent = JSON.stringify(reportData);
    const reportHash = crypto.createHash('sha256').update(reportContent).digest('hex');

    // Store report
    const reportResult = await pool.query(
      `INSERT INTO therapy_reports
       (family_unit_id, tenant_id, report_period_start, report_period_end,
        report_type, report_data, consent_channels, report_hash, legal_disclaimer_version)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING id`,
      [familyUnitId, tenantId, periodStart, periodEnd,
       getDuration(periodStart, periodEnd),
       JSON.stringify(reportData), JSON.stringify(channels), reportHash, LEGAL_DISCLAIMER_VERSION]
    );

    const reportId = reportResult.rows[0].id;

    return {
      reportId,
      reportData,
      reportHash,
      legalDisclaimer: LEGAL_DISCLAIMER,
      legalDisclaimerVersion: LEGAL_DISCLAIMER_VERSION,
      consentedChannels,
      periodStart,
      periodEnd
    };
  } catch (err) {
    console.error('[TherapyReport] generateReport failed:', err.message);
    Sentry.captureException(err);
    return { error: true, message: 'Failed to generate report' };
  }
}

function getDuration(start, end) {
  const diffDays = (new Date(end) - new Date(start)) / (1000 * 60 * 60 * 24);
  return diffDays > 14 ? 'monthly' : 'weekly';
}

// ── SUBMIT CONSENT ──────────────────────────────────────────

async function submitConsent(reportId, consenterId, channelsConsented) {
  try {
    await pool.query(
      `UPDATE therapy_reports SET
         consent_given_by = $1, consent_given_at = NOW(), consent_channels = $2
       WHERE id = $3`,
      [consenterId, JSON.stringify(channelsConsented), reportId]
    );

    // Audit trail
    await pool.query(
      `INSERT INTO therapy_consent_audit
       (report_id, consenter_id, channels_consented, action)
       VALUES ($1, $2, $3, 'consent_given')`,
      [reportId, consenterId, JSON.stringify(channelsConsented)]
    );

    return { success: true, reportId };
  } catch (err) {
    console.error('[TherapyReport] submitConsent failed:', err.message);
    Sentry.captureException(err);
    return { error: true, message: 'Failed to submit consent' };
  }
}

// ── PREVIEW REPORT ──────────────────────────────────────────

async function previewReport(reportId, familyUnitId) {
  try {
    const result = await pool.query(
      'SELECT * FROM therapy_reports WHERE id = $1 AND family_unit_id = $2',
      [reportId, familyUnitId]
    );
    if (result.rows.length === 0) return { error: true, message: 'Report not found' };

    const report = result.rows[0];

    await pool.query(
      'UPDATE therapy_reports SET previewed_by_family = true, previewed_at = NOW() WHERE id = $1',
      [reportId]
    );

    // Audit trail
    await pool.query(
      `INSERT INTO therapy_consent_audit
       (report_id, consenter_id, action)
       VALUES ($1, $2, 'preview_requested')`,
      [reportId, report.consent_given_by]
    );

    return {
      reportId,
      reportData: report.report_data,
      reportHash: report.report_hash,
      legalDisclaimer: LEGAL_DISCLAIMER,
      legalDisclaimerVersion: report.legal_disclaimer_version,
      consentChannels: report.consent_channels,
      periodStart: report.report_period_start,
      periodEnd: report.report_period_end,
      previewed: true
    };
  } catch (err) {
    console.error('[TherapyReport] previewReport failed:', err.message);
    return { error: true, message: 'Failed to preview report' };
  }
}

// ── SEND TO THERAPIST ───────────────────────────────────────

async function sendToTherapist(reportId, therapistEmail, senderId) {
  try {
    const report = await pool.query(
      'SELECT * FROM therapy_reports WHERE id = $1',
      [reportId]
    );
    if (report.rows.length === 0) return { error: true, message: 'Report not found' };

    const r = report.rows[0];

    // Require consent and preview before sending
    if (!r.consent_given_at) {
      return { error: true, message: 'Consent required before sending report' };
    }
    if (!r.previewed_by_family) {
      return { error: true, message: 'Family must preview report before sending to therapist' };
    }

    // Send email (via emailService — console log for pilot)
    const emailService = require('./emailService');
    await emailService.sendEmail({
      to: therapistEmail,
      subject: `ASCEN BreathWorx Family Therapy Report — ${r.report_period_start} to ${r.report_period_end}`,
      body: `Report ID: ${reportId}\nReport Hash: ${r.report_hash}\n\n${LEGAL_DISCLAIMER}\n\nReport data attached.`
    });

    await pool.query(
      'UPDATE therapy_reports SET therapist_email = $1, sent_to_therapist_at = NOW() WHERE id = $2',
      [therapistEmail, reportId]
    );

    // Audit trail
    await pool.query(
      `INSERT INTO therapy_consent_audit
       (report_id, consenter_id, action)
       VALUES ($1, $2, 'report_sent')`,
      [reportId, senderId]
    );

    return { success: true, reportId, sentTo: therapistEmail };
  } catch (err) {
    console.error('[TherapyReport] sendToTherapist failed:', err.message);
    Sentry.captureException(err);
    return { error: true, message: 'Failed to send report' };
  }
}

// ── GET REPORT ──────────────────────────────────────────────

async function getReport(reportId, familyUnitId) {
  try {
    const result = await pool.query(
      'SELECT * FROM therapy_reports WHERE id = $1 AND family_unit_id = $2',
      [reportId, familyUnitId]
    );
    if (result.rows.length === 0) return null;
    const report = result.rows[0];
    report.legal_disclaimer = LEGAL_DISCLAIMER;
    return report;
  } catch (err) {
    return null;
  }
}

module.exports = {
  generateReport,
  submitConsent,
  previewReport,
  sendToTherapist,
  getReport,
  LEGAL_DISCLAIMER,
  LEGAL_DISCLAIMER_VERSION
};
