// ============================================================
// valueEngine.js — Value Engine for healing economy metrics
// Computes the economic and therapeutic value generated by
// the platform. Used by AXIS for reporting and by blockchain
// for attestation value proofs.
//
// Contract addresses from contract_registry. Never hardcoded.
// ============================================================

class ValueEngine {
  constructor(pool) {
    this.pool = pool;
  }

  /**
   * Compute value report for a jurisdiction or the whole system.
   */
  async computeValueReport(options = {}) {
    const { jurisdiction, period_days = 30 } = options;

    const report = {
      period_days,
      jurisdiction: jurisdiction || process.env.ASCEN_JURISDICTION || 'all',
      generated_at: new Date().toISOString(),
      session_metrics: null,
      regulation_metrics: null,
      engagement_metrics: null,
      blockchain_metrics: null
    };

    try {
      // Session metrics
      const sessions = await this.pool.query(
        `SELECT
           COUNT(*) as total_sessions,
           COUNT(DISTINCT user_id) as unique_users,
           SUM(active_duration_seconds) as total_seconds,
           AVG(coherence_score) as avg_coherence,
           AVG(coherence_end) as avg_coherence_end,
           SUM(CASE WHEN panic_event THEN 1 ELSE 0 END) as panic_sessions,
           SUM(CASE WHEN exit_type = 'normal' THEN 1 ELSE 0 END) as completed_sessions
         FROM session_completions
         WHERE completed_at > NOW() - ($1 || ' days')::INTERVAL`,
        [period_days]
      );
      const s = sessions.rows[0];
      report.session_metrics = {
        total_sessions: parseInt(s.total_sessions) || 0,
        unique_users: parseInt(s.unique_users) || 0,
        total_breath_hours: Math.round((parseInt(s.total_seconds) || 0) / 3600 * 10) / 10,
        avg_coherence: Math.round((parseFloat(s.avg_coherence) || 0) * 1000) / 1000,
        completion_rate: parseInt(s.total_sessions) > 0
          ? Math.round((parseInt(s.completed_sessions) / parseInt(s.total_sessions)) * 100) / 100
          : 0
      };

      // Regulation metrics
      const regulation = await this.pool.query(
        `SELECT
           AVG(time_to_regulation_sec) as avg_ttr,
           COUNT(CASE WHEN coherence_trajectory = 'improving' THEN 1 END) as improving,
           COUNT(CASE WHEN coherence_trajectory = 'stable' THEN 1 END) as stable,
           COUNT(CASE WHEN coherence_trajectory = 'declining' THEN 1 END) as declining
         FROM session_completions
         WHERE completed_at > NOW() - ($1 || ' days')::INTERVAL
           AND time_to_regulation_sec IS NOT NULL`,
        [period_days]
      );
      const r = regulation.rows[0];
      report.regulation_metrics = {
        avg_time_to_regulation_sec: Math.round(parseFloat(r.avg_ttr) || 0),
        trajectory_distribution: {
          improving: parseInt(r.improving) || 0,
          stable: parseInt(r.stable) || 0,
          declining: parseInt(r.declining) || 0
        }
      };

      // Engagement metrics
      const engagement = await this.pool.query(
        `SELECT
           COUNT(DISTINCT u.participant_id) as active_users,
           AVG(u.total_sessions_completed) as avg_sessions_per_user
         FROM users u
         WHERE EXISTS (
           SELECT 1 FROM session_completions sc
           WHERE sc.user_id = u.participant_id
             AND sc.completed_at > NOW() - ($1 || ' days')::INTERVAL
         )`,
        [period_days]
      );
      const e = engagement.rows[0];
      report.engagement_metrics = {
        active_users: parseInt(e.active_users) || 0,
        avg_sessions_per_user: Math.round(parseFloat(e.avg_sessions_per_user) || 0)
      };

      // Blockchain metrics
      try {
        const chain = await this.pool.query(
          `SELECT
             COUNT(*) as total_queued,
             COUNT(CASE WHEN status = 'confirmed' THEN 1 END) as confirmed,
             COUNT(CASE WHEN status = 'awaiting_facilitator' THEN 1 END) as awaiting,
             COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed
           FROM attestation_queue
           WHERE created_at > NOW() - ($1 || ' days')::INTERVAL`,
          [period_days]
        );
        const c = chain.rows[0];
        report.blockchain_metrics = {
          total_queued: parseInt(c.total_queued) || 0,
          confirmed: parseInt(c.confirmed) || 0,
          awaiting_facilitator: parseInt(c.awaiting) || 0,
          failed: parseInt(c.failed) || 0
        };
      } catch (err) {
        report.blockchain_metrics = { error: err.message };
      }

    } catch (err) {
      report.error = err.message;
    }

    return report;
  }

  /**
   * Per-user value summary (for clinical dashboard).
   */
  async getUserValueSummary(userId) {
    try {
      const result = await this.pool.query(
        `SELECT
           COUNT(*) as total_sessions,
           SUM(active_duration_seconds) as total_seconds,
           AVG(coherence_score) as avg_coherence,
           MAX(coherence_score) as peak_coherence,
           AVG(time_to_regulation_sec) as avg_ttr,
           COUNT(CASE WHEN packet_hash IS NOT NULL THEN 1 END) as attested
         FROM session_completions
         WHERE user_id = $1`,
        [userId]
      );
      const r = result.rows[0];
      return {
        user_id: userId,
        total_sessions: parseInt(r.total_sessions) || 0,
        total_breath_hours: Math.round((parseInt(r.total_seconds) || 0) / 3600 * 10) / 10,
        avg_coherence: Math.round((parseFloat(r.avg_coherence) || 0) * 1000) / 1000,
        peak_coherence: Math.round((parseFloat(r.peak_coherence) || 0) * 1000) / 1000,
        avg_time_to_regulation: Math.round(parseFloat(r.avg_ttr) || 0),
        attested_sessions: parseInt(r.attested) || 0
      };
    } catch (err) {
      return { user_id: userId, error: err.message };
    }
  }
}

module.exports = { ValueEngine };
