'use strict';

const COACHING_FIRMWARE_LIBRARY = [

  // ============================================================
  // DOMAIN: showing_up (40 entries)
  // Theme: Consistency is love. Presence is the practice, not the guarantee.
  // ============================================================

  // showing_up — gate_1 (15 entries)
  {
    id: 'cf_showing_up_001',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "You showed up today. That matters more than you know.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'presence'],
  },
  {
    id: 'cf_showing_up_002',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "{parent_name}, you just gave yourself a few minutes of stillness. That's not small.",
    references_child: false,
    post_release: false,
    tags: ['self_care', 'presence'],
  },
  {
    id: 'cf_showing_up_003',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "Every breath you took just now was a choice to be here. You made that choice {breath_count} times.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'awareness'],
  },
  {
    id: 'cf_showing_up_004',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "Showing up for yourself is how you practice showing up for {child_name}.",
    references_child: true,
    post_release: false,
    tags: ['consistency', 'presence', 'parenting'],
  },
  {
    id: 'cf_showing_up_005',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "You didn't skip today. That's the practice.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'discipline'],
  },
  {
    id: 'cf_showing_up_006',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "This is session {session_number}. Each one is you saying yes again.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'commitment'],
  },
  {
    id: 'cf_showing_up_007',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "Some days showing up feels easy. Some days it's the hardest thing. Both count.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'honesty'],
  },
  {
    id: 'cf_showing_up_008',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "Nobody sees this work you're doing right now. But it's real.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'self_worth'],
  },
  {
    id: 'cf_showing_up_009',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "{parent_name}, the fact that you're here says something about who you're becoming.",
    references_child: false,
    post_release: false,
    tags: ['identity', 'presence'],
  },
  {
    id: 'cf_showing_up_010',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "{child_name} doesn't know about this breath session. But the person you're building — they'll meet that person.",
    references_child: true,
    post_release: false,
    tags: ['presence', 'parenting', 'growth'],
  },
  {
    id: 'cf_showing_up_011',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "You just chose stillness over noise. That's a skill you're practicing.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'self_regulation'],
  },
  {
    id: 'cf_showing_up_012',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "Consistency isn't perfection. It's coming back. You came back today.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'self_compassion'],
  },
  {
    id: 'cf_showing_up_013',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "There was a version of today where you didn't do this. But here you are.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'presence'],
  },
  {
    id: 'cf_showing_up_014',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "{breath_count} breaths. That's {breath_count} times you chose to stay present.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'awareness'],
  },
  {
    id: 'cf_showing_up_015',
    domain: 'showing_up',
    min_gate: 'gate_1',
    template: "Showing up when it's hard is different from showing up when it's easy. Both are real.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'honesty'],
  },

  // showing_up — gate_2 (12 entries)
  {
    id: 'cf_showing_up_016',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "Presence is a practice, not a performance. You're not here to impress anyone with your breathing — just do it.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'authenticity'],
  },
  {
    id: 'cf_showing_up_017',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "Some people wait until everything feels right to start. You started from where you are.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'courage'],
  },
  {
    id: 'cf_showing_up_018',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "{parent_name}, showing up when the day was rough is worth noticing. You did that.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'self_compassion'],
  },
  {
    id: 'cf_showing_up_019',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "What you're building in these sessions — the steadiness, the rhythm — that's yours to keep.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'identity'],
  },
  {
    id: 'cf_showing_up_020',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "{child_name} is growing every day. So are you. Growing doesn't look the same for everyone.",
    references_child: true,
    post_release: false,
    tags: ['growth', 'parenting'],
  },
  {
    id: 'cf_showing_up_021',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "You're learning to be still on purpose. That's different from being stuck. Feel the difference.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'awareness'],
  },
  {
    id: 'cf_showing_up_022',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "Nobody handed you a manual for this. You're writing your own — one session at a time.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'self_authoring'],
  },
  {
    id: 'cf_showing_up_023',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "The world outside this moment is loud. You just chose quiet. That took something.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'courage'],
  },
  {
    id: 'cf_showing_up_024',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "{parent_name}, being a parent from a distance takes a different kind of strength. You're practicing that strength.",
    references_child: false,
    post_release: false,
    tags: ['parenting', 'presence'],
  },
  {
    id: 'cf_showing_up_025',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "Showing up for something when results aren't immediate — that's character. You're building it.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'patience'],
  },
  {
    id: 'cf_showing_up_026',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "Think about the version of you from session one. That person decided to begin. Today you decided to continue.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'consistency'],
  },
  {
    id: 'cf_showing_up_027',
    domain: 'showing_up',
    min_gate: 'gate_2',
    template: "The rhythm of your breath just now — that steadiness is something {child_name} will feel in your voice someday.",
    references_child: true,
    post_release: false,
    tags: ['presence', 'parenting', 'connection'],
  },

  // showing_up — gate_3 (8 entries)
  {
    id: 'cf_showing_up_028',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "You're learning that presence isn't about fixing a moment. It's about being in it without running.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'emotional_regulation'],
  },
  {
    id: 'cf_showing_up_029',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "When {child_name} is upset, your calm won't fix it immediately. But it gives them something solid to lean against.",
    references_child: true,
    post_release: false,
    tags: ['co_regulation', 'parenting'],
  },
  {
    id: 'cf_showing_up_030',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "Showing up isn't about the big moments. It's the Tuesday after the hard Monday. It's the quiet consistency.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'honesty'],
  },
  {
    id: 'cf_showing_up_031',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "{parent_name}, you're becoming someone who stays. Not because it's easy, but because you've practiced staying.",
    references_child: false,
    post_release: false,
    tags: ['identity', 'consistency'],
  },
  {
    id: 'cf_showing_up_032',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "Presence doesn't mean having all the answers when {child_name} looks at you. It means not looking away.",
    references_child: true,
    post_release: false,
    tags: ['presence', 'parenting', 'vulnerability'],
  },
  {
    id: 'cf_showing_up_033',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "You've been practicing being here — in your body, in the moment. That practice changes how you enter a room.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'embodiment'],
  },
  {
    id: 'cf_showing_up_034',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "Consistency doesn't erase the past. It builds something next to it. Both are real.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'honesty', 'growth'],
  },
  {
    id: 'cf_showing_up_035',
    domain: 'showing_up',
    min_gate: 'gate_3',
    template: "Your child's experience of you is still being written. These breaths are part of the draft.",
    references_child: true,
    post_release: false,
    tags: ['presence', 'parenting', 'hope'],
  },

  // showing_up — gate_4 (5 entries)
  {
    id: 'cf_showing_up_036',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "You've been showing up for a while now. Not perfectly. Consistently. That's the harder one.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'honesty', 'growth'],
  },
  {
    id: 'cf_showing_up_037',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "There may come a day when {child_name} doesn't want your presence. Showing up anyway — with respect for their space — is advanced practice.",
    references_child: true,
    post_release: false,
    tags: ['presence', 'parenting', 'letting_go'],
  },
  {
    id: 'cf_showing_up_038',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "{parent_name}, the person who started these sessions and the person finishing this one aren't the same. Growth happened in the gaps you couldn't see.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'self_awareness'],
  },
  {
    id: 'cf_showing_up_039',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "Presence isn't a trophy. It's a daily choice. Some of the most meaningful things you'll do are invisible to everyone else.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'humility'],
  },
  {
    id: 'cf_showing_up_040',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "You've learned something rare: how to sit with discomfort and not leave. {child_name} will benefit from that — even if they never know the work behind it.",
    references_child: true,
    post_release: false,
    tags: ['presence', 'parenting', 'resilience'],
  },

  // ============================================================
  // DOMAIN: emotional_vocabulary (40 entries)
  // Theme: Name feelings without fixing them. Hard feelings aren't emergencies.
  // ============================================================

  // emotional_vocabulary — gate_1 (15 entries)
  {
    id: 'cf_emotional_vocabulary_001',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "After breathing, check in: what's one word for how you feel right now? Just one.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_002',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "Angry, tired, hopeful, unsure — whatever you're feeling right now has a name. Naming it is the first step.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'emotional_awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_003',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "Feelings aren't problems to solve. They're weather to notice.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_004',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "{parent_name}, if someone asked you how you're doing right now, what would the honest answer be? Practice saying it — even to yourself.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'honesty'],
  },
  {
    id: 'cf_emotional_vocabulary_005',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "There's a difference between 'I'm fine' and what's really going on. You just made space to notice the real thing.",
    references_child: false,
    post_release: false,
    tags: ['awareness', 'authenticity'],
  },
  {
    id: 'cf_emotional_vocabulary_006',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "Sadness is not weakness. Anger is not a flaw. They're information.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'naming'],
  },
  {
    id: 'cf_emotional_vocabulary_007',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "You can feel two things at once. Hopeful and afraid. Missing {child_name} and grateful for this moment. Both are true.",
    references_child: true,
    post_release: false,
    tags: ['complexity', 'acceptance'],
  },
  {
    id: 'cf_emotional_vocabulary_008',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "Right now, after {breath_count} breaths, your body knows something your mind is still catching up to. What is it?",
    references_child: false,
    post_release: false,
    tags: ['embodiment', 'awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_009',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "A hard feeling doesn't mean something is wrong. Sometimes it means something matters.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'meaning'],
  },
  {
    id: 'cf_emotional_vocabulary_010',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "You can notice a feeling without doing anything about it. That's a skill most people never learn.",
    references_child: false,
    post_release: false,
    tags: ['awareness', 'self_regulation'],
  },
  {
    id: 'cf_emotional_vocabulary_011',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "When you think about {child_name}, what feeling shows up first? Don't judge it. Just notice.",
    references_child: true,
    post_release: false,
    tags: ['naming', 'parenting'],
  },
  {
    id: 'cf_emotional_vocabulary_012',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "'I feel frustrated' is different from 'I am frustrated.' One describes weather. The other says it's your identity. Try the first one.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'identity'],
  },
  {
    id: 'cf_emotional_vocabulary_013',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "Today might have been heavy. That's okay. Naming the weight doesn't add to it.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'acceptance'],
  },
  {
    id: 'cf_emotional_vocabulary_014',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "{parent_name}, every feeling passes through. Even the big ones. Especially the big ones.",
    references_child: false,
    post_release: false,
    tags: ['impermanence', 'acceptance'],
  },
  {
    id: 'cf_emotional_vocabulary_015',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_1',
    template: "You just spent a few minutes breathing. Whatever showed up during that time — frustration, peace, boredom — it belongs.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'awareness'],
  },

  // emotional_vocabulary — gate_2 (12 entries)
  {
    id: 'cf_emotional_vocabulary_016',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Underneath anger there's usually something softer — disappointment, hurt, fear. When you're ready, look underneath.",
    references_child: false,
    post_release: false,
    tags: ['depth', 'awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_017',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Kids learn to name feelings by hearing someone else do it first. You're practicing something {child_name} will one day borrow.",
    references_child: true,
    post_release: false,
    tags: ['modeling', 'parenting'],
  },
  {
    id: 'cf_emotional_vocabulary_018',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Some feelings are loud — anger, irritation. Some are quiet — loneliness, longing. Both deserve your attention.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'depth'],
  },
  {
    id: 'cf_emotional_vocabulary_019',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Guilt can be useful if it helps you move. It becomes heavy when you carry it without examining it. Which is it for you today?",
    references_child: false,
    post_release: false,
    tags: ['guilt', 'reflection'],
  },
  {
    id: 'cf_emotional_vocabulary_020',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "{parent_name}, missing {child_name} isn't a flaw. It's proof of connection. Let yourself feel it without rushing past it.",
    references_child: true,
    post_release: false,
    tags: ['grief', 'connection', 'parenting'],
  },
  {
    id: 'cf_emotional_vocabulary_021',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "When a hard day hits, see if you can find the specific feeling — not just 'bad' but what kind of bad. That specificity is power.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'specificity'],
  },
  {
    id: 'cf_emotional_vocabulary_022',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Numbness is also a feeling. If that's where you are, it's okay to say 'I feel numb today.' That counts.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'acceptance', 'honesty'],
  },
  {
    id: 'cf_emotional_vocabulary_023',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Feeling positive after breathing isn't the point. Sometimes breathing just helps you feel what's actually there.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'honesty'],
  },
  {
    id: 'cf_emotional_vocabulary_024',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "The space between a feeling and your reaction to it — that's where your breathing practice lives.",
    references_child: false,
    post_release: false,
    tags: ['awareness', 'self_regulation'],
  },
  {
    id: 'cf_emotional_vocabulary_025',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "Shame says 'I am bad.' Guilt says 'I did something I want to change.' Learning the difference changes everything.",
    references_child: false,
    post_release: false,
    tags: ['shame', 'guilt', 'naming'],
  },
  {
    id: 'cf_emotional_vocabulary_026',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "When you think about the future with {child_name}, notice if it's hope or anxiety. They can feel similar. Naming the right one matters.",
    references_child: true,
    post_release: false,
    tags: ['naming', 'parenting', 'awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_027',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_2',
    template: "A feeling you can name is a feeling you can sit with. A feeling you can sit with doesn't run you.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'self_regulation'],
  },

  // emotional_vocabulary — gate_3 (8 entries)
  {
    id: 'cf_emotional_vocabulary_028',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "When {child_name} is upset, they may not have words for it yet. Imagine if someone had helped you name your feelings when you were small. You can be that person.",
    references_child: true,
    post_release: false,
    tags: ['modeling', 'parenting', 'empathy'],
  },
  {
    id: 'cf_emotional_vocabulary_029',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "Feelings aren't emergencies. Even the big, loud, uncomfortable ones. You've been practicing being steady in the middle of them.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'self_regulation'],
  },
  {
    id: 'cf_emotional_vocabulary_030',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "A child's tantrum is often an unnamed feeling with nowhere to go. Your calm presence gives it a place to land.",
    references_child: true,
    post_release: false,
    tags: ['co_regulation', 'parenting'],
  },
  {
    id: 'cf_emotional_vocabulary_031',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "{parent_name}, you're getting better at being honest about what you feel. That honesty is a form of strength most people avoid.",
    references_child: false,
    post_release: false,
    tags: ['honesty', 'growth', 'vulnerability'],
  },
  {
    id: 'cf_emotional_vocabulary_032',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "Sometimes love and grief are the same feeling. That's not confusion — that's the truth of caring about someone while apart.",
    references_child: false,
    post_release: false,
    tags: ['grief', 'love', 'complexity'],
  },
  {
    id: 'cf_emotional_vocabulary_033',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "You can hold sadness without it pulling you under. That's not denial. That's capacity — and you've been building it.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'resilience'],
  },
  {
    id: 'cf_emotional_vocabulary_034',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "If {child_name} tells you they're angry at you someday, your job isn't to talk them out of it. It's to stay.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'presence', 'acceptance'],
  },
  {
    id: 'cf_emotional_vocabulary_035',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_3',
    template: "Naming a hard feeling out loud — 'I'm lonely today' — doesn't make it bigger. It makes it honest. Honest things are easier to carry.",
    references_child: false,
    post_release: false,
    tags: ['naming', 'honesty', 'vulnerability'],
  },

  // emotional_vocabulary — gate_4 (5 entries)
  {
    id: 'cf_emotional_vocabulary_036',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "You've built something not everyone has: the ability to feel deeply and stay grounded. Those don't cancel each other out.",
    references_child: false,
    post_release: false,
    tags: ['depth', 'resilience', 'growth'],
  },
  {
    id: 'cf_emotional_vocabulary_037',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "One day {child_name} may bring you a feeling you don't know how to hold. That's okay. You can witness it without carrying it.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'presence', 'humility'],
  },
  {
    id: 'cf_emotional_vocabulary_038',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "Emotional honesty isn't about dumping feelings on other people. It's about knowing what's yours so you don't hand it to {child_name} by accident.",
    references_child: true,
    post_release: false,
    tags: ['boundaries', 'parenting', 'self_awareness'],
  },
  {
    id: 'cf_emotional_vocabulary_039',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "{parent_name}, you've practiced naming what's hard. That's rare. Most people spend a lifetime avoiding it.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'naming', 'courage'],
  },
  {
    id: 'cf_emotional_vocabulary_040',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "The vocabulary you've built for your feelings will outlast these walls. It belongs to you.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'identity', 'resilience'],
  },

  // ============================================================
  // DOMAIN: co_regulation (40 entries)
  // Theme: Your calm is a gift, not a demand. Regulation is practiced, not commanded.
  // ============================================================

  // co_regulation — gate_1 (15 entries)
  {
    id: 'cf_co_regulation_001',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "When you slow your breathing, the people around you feel it — even if they don't know why.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'presence'],
  },
  {
    id: 'cf_co_regulation_002',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "Your calm is a real thing. Not just an idea — a physical presence that changes a room.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'embodiment'],
  },
  {
    id: 'cf_co_regulation_003',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "You just practiced getting steady. That steadiness is something you can share without saying a word.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'presence'],
  },
  {
    id: 'cf_co_regulation_004',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "{parent_name}, kids pick up on the energy of the adults around them. Your calm sends a signal: 'We're okay right now.'",
    references_child: false,
    post_release: false,
    tags: ['calm', 'parenting'],
  },
  {
    id: 'cf_co_regulation_005',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "You can't breathe for {child_name}. But you can practice breathing for yourself so that when you're together, your body knows the way.",
    references_child: true,
    post_release: false,
    tags: ['calm', 'parenting', 'preparation'],
  },
  {
    id: 'cf_co_regulation_006',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "Regulation is contagious. When one person in the room is grounded, it gives everyone else something to sync to.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'connection'],
  },
  {
    id: 'cf_co_regulation_007',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "You don't regulate someone else by telling them to calm down. You do it by being calm yourself.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'modeling'],
  },
  {
    id: 'cf_co_regulation_008',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "Those {breath_count} breaths just now? They weren't just for you. They're practice for being a steady presence for {child_name}.",
    references_child: true,
    post_release: false,
    tags: ['calm', 'parenting', 'practice'],
  },
  {
    id: 'cf_co_regulation_009',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "Think of your calm like a low hum. You don't force anyone to hear it — but when you're close, they feel it.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'presence', 'metaphor'],
  },
  {
    id: 'cf_co_regulation_010',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "You practiced slowing down. That's harder than speeding up. And it's what the people closest to you benefit from most.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'patience'],
  },
  {
    id: 'cf_co_regulation_011',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "Nobody can demand calm from someone else. But you can offer it. That's what you're building.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'respect'],
  },
  {
    id: 'cf_co_regulation_012',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "{parent_name}, your body remembers this practice even when your mind forgets. That's how habits work — they show up when you're not thinking about them.",
    references_child: false,
    post_release: false,
    tags: ['embodiment', 'consistency'],
  },
  {
    id: 'cf_co_regulation_013',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "A child doesn't learn to be calm from a lecture. They learn it from standing next to someone who is.",
    references_child: false,
    post_release: false,
    tags: ['modeling', 'parenting'],
  },
  {
    id: 'cf_co_regulation_014',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "You're practicing something with no audience. That's the most honest kind of practice there is.",
    references_child: false,
    post_release: false,
    tags: ['authenticity', 'practice'],
  },
  {
    id: 'cf_co_regulation_015',
    domain: 'co_regulation',
    min_gate: 'gate_1',
    template: "The steadiness you felt at the end of that session — carry a little of it with you. Let it change how you walk into the next room.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'presence'],
  },

  // co_regulation — gate_2 (12 entries)
  {
    id: 'cf_co_regulation_016',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "When {child_name} is wound up, your first job isn't to fix them. It's to check your own body first. You've been practicing that.",
    references_child: true,
    post_release: false,
    tags: ['self_regulation', 'parenting'],
  },
  {
    id: 'cf_co_regulation_017',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "Your breathing practice doesn't just change your body. It changes the space between you and whoever you're with.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'relational'],
  },
  {
    id: 'cf_co_regulation_018',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "Imagine sitting next to {child_name} after a hard day and just breathing. Not talking, not fixing. Just breathing together. That's co-regulation.",
    references_child: true,
    post_release: false,
    tags: ['co_regulation', 'parenting', 'presence'],
  },
  {
    id: 'cf_co_regulation_019',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "{parent_name}, the calm you carry isn't passive. It's one of the most active things you can offer another human being.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'strength'],
  },
  {
    id: 'cf_co_regulation_020',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "Telling someone to calm down is a demand. Being calm near them is an invitation. You're learning to invite.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'respect', 'modeling'],
  },
  {
    id: 'cf_co_regulation_021',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "When you're regulated, you can feel other people's distress without drowning in it. That's not coldness — it's capacity.",
    references_child: false,
    post_release: false,
    tags: ['emotional_regulation', 'empathy'],
  },
  {
    id: 'cf_co_regulation_022',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "Your breathing changes your heart rate. Your heart rate changes your voice. Your voice is one of the first things {child_name} responds to.",
    references_child: true,
    post_release: false,
    tags: ['embodiment', 'parenting', 'connection'],
  },
  {
    id: 'cf_co_regulation_023',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "A child's nervous system looks for a steady adult. Not a perfect one — just steadier than the storm.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'parenting'],
  },
  {
    id: 'cf_co_regulation_024',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "Every time you choose to slow down instead of react, you're strengthening a muscle. That muscle shows up in relationships.",
    references_child: false,
    post_release: false,
    tags: ['self_regulation', 'relational'],
  },
  {
    id: 'cf_co_regulation_025',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "The people around you can't see your breathing practice. But they can feel the difference in how you respond.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'modeling'],
  },
  {
    id: 'cf_co_regulation_026',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "{parent_name}, regulating yourself in the middle of chaos is one of the hardest and most generous things you can do for the people you love.",
    references_child: false,
    post_release: false,
    tags: ['self_regulation', 'love'],
  },
  {
    id: 'cf_co_regulation_027',
    domain: 'co_regulation',
    min_gate: 'gate_2',
    template: "Your calm doesn't erase {child_name}'s hard feelings. It just makes room for them to have those feelings safely.",
    references_child: true,
    post_release: false,
    tags: ['calm', 'parenting', 'safety'],
  },

  // co_regulation — gate_3 (8 entries)
  {
    id: 'cf_co_regulation_028',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "{child_name} may not match your calm right away. That doesn't mean it isn't working. Regulation happens on its own timeline.",
    references_child: true,
    post_release: false,
    tags: ['patience', 'parenting', 'co_regulation'],
  },
  {
    id: 'cf_co_regulation_029',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "When a child is dysregulated, they need your body to be saying something different than theirs. That's the gift of your practice.",
    references_child: false,
    post_release: false,
    tags: ['co_regulation', 'parenting', 'embodiment'],
  },
  {
    id: 'cf_co_regulation_030',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "Sometimes co-regulation looks like sitting quietly in the same room. Sometimes it's a hand on a shoulder. The form changes — the steadiness doesn't.",
    references_child: false,
    post_release: false,
    tags: ['co_regulation', 'flexibility'],
  },
  {
    id: 'cf_co_regulation_031',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "{parent_name}, your regulated presence is especially powerful after conflict. Not as a weapon — as a bridge.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'repair', 'relational'],
  },
  {
    id: 'cf_co_regulation_032',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "If {child_name} is angry at you, your calm isn't about dismissing their anger. It's about showing them their anger won't push you away.",
    references_child: true,
    post_release: false,
    tags: ['co_regulation', 'parenting', 'safety'],
  },
  {
    id: 'cf_co_regulation_033',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "Regulation isn't a performance. If you're calm because you stuffed everything down, that's not what we're building. Real regulation includes what you feel.",
    references_child: false,
    post_release: false,
    tags: ['authenticity', 'self_regulation'],
  },
  {
    id: 'cf_co_regulation_034',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "The hardest co-regulation is with people who don't want it. Offering calm to someone who's pushing back takes everything you've practiced.",
    references_child: false,
    post_release: false,
    tags: ['co_regulation', 'resilience'],
  },
  {
    id: 'cf_co_regulation_035',
    domain: 'co_regulation',
    min_gate: 'gate_3',
    template: "Your child doesn't learn regulation by hearing about it. They learn it in the moments when you're regulated and they're not — and you stay.",
    references_child: true,
    post_release: false,
    tags: ['modeling', 'parenting', 'consistency'],
  },

  // co_regulation — gate_4 (5 entries)
  {
    id: 'cf_co_regulation_036',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "There will be moments where your calm isn't enough for {child_name}. That doesn't mean it was wasted. Sometimes seeds take time.",
    references_child: true,
    post_release: false,
    tags: ['patience', 'parenting', 'honesty'],
  },
  {
    id: 'cf_co_regulation_037',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "You've been learning to regulate yourself without anyone holding space for you. That's advanced work. Let that land.",
    references_child: false,
    post_release: false,
    tags: ['self_regulation', 'growth', 'self_compassion'],
  },
  {
    id: 'cf_co_regulation_038',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "{parent_name}, the calm you've practiced isn't just for crisis moments. It's for the quiet moments too — bedtime, car rides, meals. The ordinary ones are where it matters most.",
    references_child: false,
    post_release: false,
    tags: ['calm', 'everyday', 'parenting'],
  },
  {
    id: 'cf_co_regulation_039',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "You can't regulate your child into feeling safe. You can be the kind of steady that allows safety to build over time.",
    references_child: true,
    post_release: false,
    tags: ['co_regulation', 'parenting', 'patience'],
  },
  {
    id: 'cf_co_regulation_040',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "Your nervous system has practiced something most adults never practice on purpose. Whatever comes next, that work is in you.",
    references_child: false,
    post_release: false,
    tags: ['resilience', 'identity', 'growth'],
  },

  // ============================================================
  // DOMAIN: letting_go (40 entries)
  // Theme: Your child's journey is theirs. Control your mindset, hold the rest with open hands.
  // ============================================================

  // letting_go — gate_1 (15 entries)
  {
    id: 'cf_letting_go_001',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "You can care deeply about something and still not control how it goes. Both are true.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'openness'],
  },
  {
    id: 'cf_letting_go_002',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "Letting go isn't giving up. It's holding with open hands instead of a clenched fist.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'metaphor'],
  },
  {
    id: 'cf_letting_go_003',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "{parent_name}, you can love {child_name} with everything you have and still not control their experience. That's parenthood.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'acceptance'],
  },
  {
    id: 'cf_letting_go_004',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "The breath you just released — notice how your body let go of it without effort. Some things work like that.",
    references_child: false,
    post_release: false,
    tags: ['metaphor', 'awareness'],
  },
  {
    id: 'cf_letting_go_005',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "There are things you can influence and things you can't. Your peace depends on knowing which is which.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'wisdom'],
  },
  {
    id: 'cf_letting_go_006',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "Worrying is not the same as caring. You can care about {child_name} without wearing yourself out with worry.",
    references_child: true,
    post_release: false,
    tags: ['worry', 'parenting', 'acceptance'],
  },
  {
    id: 'cf_letting_go_007',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "Today you practiced releasing tension in your body. That's the same skill as releasing what you can't control in your life.",
    references_child: false,
    post_release: false,
    tags: ['metaphor', 'embodiment'],
  },
  {
    id: 'cf_letting_go_008',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "You can't be in two places at once. What you can do is take care of the place you're in.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'acceptance'],
  },
  {
    id: 'cf_letting_go_009',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "{parent_name}, not everything rests on your shoulders. That's not a criticism — it's permission.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'self_compassion'],
  },
  {
    id: 'cf_letting_go_010',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "The exhale is the letting go part of breathing. You just practiced it {breath_count} times.",
    references_child: false,
    post_release: false,
    tags: ['metaphor', 'awareness'],
  },
  {
    id: 'cf_letting_go_011',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "Some things are yours to carry. Some things are yours to put down. Wisdom is knowing the difference.",
    references_child: false,
    post_release: false,
    tags: ['wisdom', 'acceptance'],
  },
  {
    id: 'cf_letting_go_012',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "Tomorrow can wait. Right now is enough to hold.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'acceptance'],
  },
  {
    id: 'cf_letting_go_013',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "{child_name} is growing in ways you can't always see. Trust doesn't mean certainty — it means holding space for what you don't know.",
    references_child: true,
    post_release: false,
    tags: ['trust', 'parenting'],
  },
  {
    id: 'cf_letting_go_014',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "Holding on tightly to what you love doesn't keep it closer. Sometimes it just tires your hands.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'metaphor'],
  },
  {
    id: 'cf_letting_go_015',
    domain: 'letting_go',
    min_gate: 'gate_1',
    template: "There is peace in doing what you can and releasing the rest. You just practiced the releasing part.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'presence'],
  },

  // letting_go — gate_2 (12 entries)
  {
    id: 'cf_letting_go_016',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "{child_name}'s journey will include things you can't plan for. That's not a flaw in the system — it's how growing works.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'acceptance', 'trust'],
  },
  {
    id: 'cf_letting_go_017',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "Control feels safe, but it's heavy. What if you traded some of that weight for trust — not blind trust, just a little more?",
    references_child: false,
    post_release: false,
    tags: ['trust', 'acceptance'],
  },
  {
    id: 'cf_letting_go_018',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "{parent_name}, some of the hardest nights come from trying to hold what's not in your hands. You can still care deeply and loosen the grip.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'self_compassion'],
  },
  {
    id: 'cf_letting_go_019',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "You can write a letter, make a call, say a prayer, breathe a breath — and then let the rest be. That's enough.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'sufficiency'],
  },
  {
    id: 'cf_letting_go_020',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "What {child_name} is learning right now — from caregivers, from school, from life — is part of their story. You're part of it too, not all of it.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'trust', 'humility'],
  },
  {
    id: 'cf_letting_go_021',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "Letting go of outcomes doesn't mean letting go of effort. You can give everything and still release the result.",
    references_child: false,
    post_release: false,
    tags: ['effort', 'acceptance'],
  },
  {
    id: 'cf_letting_go_022',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "Frustration often comes from wanting to control something that isn't yours. Name the thing. Then ask: is this mine to hold?",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'awareness'],
  },
  {
    id: 'cf_letting_go_023',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "The hardest part of loving someone from a distance is accepting the distance. You don't owe it approval. Just stop fighting the fact of it.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'grief'],
  },
  {
    id: 'cf_letting_go_024',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "Your mind will replay things you wish you could change. When it does, breathe like you just did. Return to now.",
    references_child: false,
    post_release: false,
    tags: ['rumination', 'presence'],
  },
  {
    id: 'cf_letting_go_025',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "{parent_name}, the past is not a room you can re-enter and rearrange. But the present — you just showed up for that.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'presence'],
  },
  {
    id: 'cf_letting_go_026',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "Every exhale is a small surrender. Not defeat — release. You practiced that {breath_count} times today.",
    references_child: false,
    post_release: false,
    tags: ['metaphor', 'acceptance'],
  },
  {
    id: 'cf_letting_go_027',
    domain: 'letting_go',
    min_gate: 'gate_2',
    template: "If you could control {child_name}'s whole world, they'd never learn to navigate it. Some space is a form of love.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'trust', 'acceptance'],
  },

  // letting_go — gate_3 (8 entries)
  {
    id: 'cf_letting_go_028',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "{child_name} is building their own relationship with the world. Your job is to be a steady part of that world, not the whole map.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'trust', 'humility'],
  },
  {
    id: 'cf_letting_go_029',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "Letting go of what you imagined parenthood looking like is grief work. It's real. And it's separate from how much you love {child_name}.",
    references_child: true,
    post_release: false,
    tags: ['grief', 'parenting', 'acceptance'],
  },
  {
    id: 'cf_letting_go_030',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "{parent_name}, some of the peace you're looking for is on the other side of acceptance. Not acceptance of everything — just of what's true today.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'peace'],
  },
  {
    id: 'cf_letting_go_031',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "Your child may develop strengths you didn't give them and carry burdens you didn't cause. That's the complexity of being a separate person.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'humility', 'acceptance'],
  },
  {
    id: 'cf_letting_go_032',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "There's a version of strength that's about holding on. There's another that's about knowing when to let go. You're practicing both.",
    references_child: false,
    post_release: false,
    tags: ['strength', 'acceptance'],
  },
  {
    id: 'cf_letting_go_033',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "If you spend all your energy trying to control what happens, you have nothing left for how you respond to what happens. Save some for the response.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'self_regulation'],
  },
  {
    id: 'cf_letting_go_034',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "The image of the parent you thought you'd be and the parent you actually are — both deserve respect. Let the first one rest.",
    references_child: false,
    post_release: false,
    tags: ['grief', 'self_compassion', 'identity'],
  },
  {
    id: 'cf_letting_go_035',
    domain: 'letting_go',
    min_gate: 'gate_3',
    template: "Open hands can still hold things. They just don't crush them.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'metaphor'],
  },

  // letting_go — gate_4 (5 entries)
  {
    id: 'cf_letting_go_036',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "You've practiced releasing tension, releasing breath, releasing the grip on perfection. That's not loss. That's freedom.",
    references_child: false,
    post_release: false,
    tags: ['acceptance', 'growth', 'freedom'],
  },
  {
    id: 'cf_letting_go_037',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "{child_name} may one day make choices you don't understand. Your steady love — not your approval — is what they'll remember.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'acceptance', 'love'],
  },
  {
    id: 'cf_letting_go_038',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "{parent_name}, holding the future with open hands is the bravest kind of hope. Not certainty — openness.",
    references_child: false,
    post_release: false,
    tags: ['hope', 'acceptance', 'courage'],
  },
  {
    id: 'cf_letting_go_039',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "You've spent these sessions learning to be present without controlling. That's the kind of parent, the kind of person, who changes things just by being in the room.",
    references_child: false,
    post_release: false,
    tags: ['presence', 'identity', 'growth'],
  },
  {
    id: 'cf_letting_go_040',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "Whatever happens next — you've already done something real. You chose to practice being human on purpose. That's yours.",
    references_child: false,
    post_release: false,
    tags: ['identity', 'growth', 'acceptance'],
  },

  // ============================================================
  // DOMAIN: repair (40 entries)
  // Theme: Rupture is not failure. Coming back is the skill. Growth is not linear.
  // ============================================================

  // repair — gate_1 (15 entries)
  {
    id: 'cf_repair_001',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "Everyone makes mistakes. What matters is what happens next.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'growth'],
  },
  {
    id: 'cf_repair_002',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "Coming back after a hard moment is harder than not messing up in the first place. And it matters more.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'courage'],
  },
  {
    id: 'cf_repair_003',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "{parent_name}, if you had a rough day, that doesn't erase the good ones. It just means today was rough.",
    references_child: false,
    post_release: false,
    tags: ['self_compassion', 'perspective'],
  },
  {
    id: 'cf_repair_004',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "Growth doesn't look like a straight line. It looks like a path that wanders and comes back. You're on it.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'honesty'],
  },
  {
    id: 'cf_repair_005',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "The fact that you're here after a hard stretch says something. You didn't quit. Sit with that for a second.",
    references_child: false,
    post_release: false,
    tags: ['consistency', 'repair'],
  },
  {
    id: 'cf_repair_006',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "A setback is not a starting over. It's a coming back. Different things.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'perspective'],
  },
  {
    id: 'cf_repair_007',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "Being perfect for {child_name} isn't the goal. Being someone who comes back — that's the goal.",
    references_child: true,
    post_release: false,
    tags: ['repair', 'parenting'],
  },
  {
    id: 'cf_repair_008',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "If you missed a session or a call or a moment — you're here now. That's the only place anything starts.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'presence'],
  },
  {
    id: 'cf_repair_009',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "{parent_name}, being hard on yourself doesn't make you better. Being honest with yourself does.",
    references_child: false,
    post_release: false,
    tags: ['self_compassion', 'honesty'],
  },
  {
    id: 'cf_repair_010',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "A crack doesn't ruin a bowl. Sometimes it's where the light gets in. Sometimes it's just a crack. Both are okay.",
    references_child: false,
    post_release: false,
    tags: ['imperfection', 'acceptance'],
  },
  {
    id: 'cf_repair_011',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "You don't earn worth by never falling. You build it by getting up. Today counts.",
    references_child: false,
    post_release: false,
    tags: ['self_worth', 'repair'],
  },
  {
    id: 'cf_repair_012',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "Your breath just now wasn't perfect. Some were slow, some were fast. You stayed with it anyway. That's the whole lesson.",
    references_child: false,
    post_release: false,
    tags: ['imperfection', 'consistency'],
  },
  {
    id: 'cf_repair_013',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "Progress isn't about never having a bad day. It's about what you do with the day after.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'repair'],
  },
  {
    id: 'cf_repair_014',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "If something went wrong recently, let yourself notice what you'd do differently — not with shame, but with curiosity.",
    references_child: false,
    post_release: false,
    tags: ['reflection', 'self_compassion'],
  },
  {
    id: 'cf_repair_015',
    domain: 'repair',
    min_gate: 'gate_1',
    template: "{child_name} doesn't need a parent who never messes up. They benefit from a parent who knows how to come back after mess-ups.",
    references_child: true,
    post_release: false,
    tags: ['repair', 'parenting', 'modeling'],
  },

  // repair — gate_2 (12 entries)
  {
    id: 'cf_repair_016',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "Saying 'I'm sorry' without defending yourself is one of the hardest skills there is. You can practice it like you practice breathing.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'vulnerability'],
  },
  {
    id: 'cf_repair_017',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "Ruptures happen in every relationship. The repair is what builds trust — not the absence of rupture.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'trust'],
  },
  {
    id: 'cf_repair_018',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "{parent_name}, guilt can be a doorway or a room you sit in forever. Use it to walk through, not to move in.",
    references_child: false,
    post_release: false,
    tags: ['guilt', 'growth', 'metaphor'],
  },
  {
    id: 'cf_repair_019',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "When you apologize to {child_name} someday — for anything, big or small — it teaches them that love includes accountability.",
    references_child: true,
    post_release: false,
    tags: ['repair', 'parenting', 'modeling'],
  },
  {
    id: 'cf_repair_020',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "The desire to do better is not the same as shame. One moves you forward. The other keeps you stuck. Know which one you're carrying.",
    references_child: false,
    post_release: false,
    tags: ['shame', 'growth', 'awareness'],
  },
  {
    id: 'cf_repair_021',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "If you lost your temper today, or shut down, or went numb — notice it. That noticing is the beginning of repair.",
    references_child: false,
    post_release: false,
    tags: ['awareness', 'repair'],
  },
  {
    id: 'cf_repair_022',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "Repair isn't about making someone forget what happened. It's about showing them what happens after.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'trust'],
  },
  {
    id: 'cf_repair_023',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "You can hold regret and forward motion at the same time. They're not opposites.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'complexity'],
  },
  {
    id: 'cf_repair_024',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "{parent_name}, the version of you that made mistakes is the same one who decided to change. Both are real. Both deserve recognition.",
    references_child: false,
    post_release: false,
    tags: ['identity', 'self_compassion'],
  },
  {
    id: 'cf_repair_025',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "A good repair has three parts: I see what happened. I own my part. Here's what I'm doing differently. You're working on all three.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'accountability'],
  },
  {
    id: 'cf_repair_026',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "Growth is not a switch you flip. It's a direction you face. Some days you walk it. Some days you crawl. Both count.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'patience'],
  },
  {
    id: 'cf_repair_027',
    domain: 'repair',
    min_gate: 'gate_2',
    template: "Every time you breathe through frustration instead of acting on it, you're choosing a different pattern. That's repair in real time.",
    references_child: false,
    post_release: false,
    tags: ['self_regulation', 'repair'],
  },

  // repair — gate_3 (8 entries)
  {
    id: 'cf_repair_028',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "When {child_name} sees you take responsibility for something, they learn that accountability isn't punishment — it's care.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'modeling', 'accountability'],
  },
  {
    id: 'cf_repair_029',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "{parent_name}, repair sometimes means accepting that the other person isn't ready to receive it. That doesn't mean the effort was wasted.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'patience', 'humility'],
  },
  {
    id: 'cf_repair_030',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "Rupture without repair teaches fear. Rupture with repair teaches resilience. You're choosing the second path.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'resilience'],
  },
  {
    id: 'cf_repair_031',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "A child who watches a parent come back after getting it wrong learns something powerful: people can change. Relationships can hold.",
    references_child: true,
    post_release: false,
    tags: ['repair', 'parenting', 'modeling'],
  },
  {
    id: 'cf_repair_032',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "Some repairs happen in conversation. Some happen slowly, through changed behavior over time. The quiet kind is just as real.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'patience'],
  },
  {
    id: 'cf_repair_033',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "You can't undo what's been done. But you can build something next to it that's strong enough to hold both the old and the new.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'growth', 'resilience'],
  },
  {
    id: 'cf_repair_034',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "If {child_name} is angry about something you did, their anger is them trusting you enough to show it. That's not easy for them either.",
    references_child: true,
    post_release: false,
    tags: ['repair', 'parenting', 'empathy'],
  },
  {
    id: 'cf_repair_035',
    domain: 'repair',
    min_gate: 'gate_3',
    template: "{parent_name}, you've been doing the slow, unglamorous work of change. Nobody gives trophies for this. But the work is real and it matters.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'self_compassion'],
  },

  // repair — gate_4 (5 entries)
  {
    id: 'cf_repair_036',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "You've practiced something rare: returning to something hard instead of running from it. That's the foundation of every strong relationship.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'resilience', 'growth'],
  },
  {
    id: 'cf_repair_037',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "When {child_name} is old enough to understand, the story of your change won't be about perfection. It'll be about persistence. That's a better story.",
    references_child: true,
    post_release: false,
    tags: ['parenting', 'growth', 'identity'],
  },
  {
    id: 'cf_repair_038',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "Some relationships will repair. Some won't. Your work on yourself is worth it either way — because it's not only about the other person.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'self_worth', 'acceptance'],
  },
  {
    id: 'cf_repair_039',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "{parent_name}, the person who started this journey and the person sitting here now have something in common: they both kept going. That's the thread that holds it together.",
    references_child: false,
    post_release: false,
    tags: ['growth', 'identity', 'resilience'],
  },
  {
    id: 'cf_repair_040',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "Repair is a lifelong practice, not a one-time event. You've started. That's the hardest part, and it's done.",
    references_child: false,
    post_release: false,
    tags: ['repair', 'growth', 'consistency'],
  },

  // ============================================================
  // REUNIFICATION ENTRIES (40 entries, all gate_4, post_release: true)
  // ============================================================

  {
    id: 'cf_reunification_001',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "Being in the same room as {child_name} again will feel like a lot of things at once. That's normal — not a sign that something's wrong.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'honesty', 'normalization'],
  },
  {
    id: 'cf_reunification_002',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "Your rhythms and {child_name}'s rhythms have been separate for a while. They won't sync up on day one. Give it time — and breath.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'patience', 'co_regulation'],
  },
  {
    id: 'cf_reunification_003',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "{child_name} may have built their own relationship with breathing or calming down. Let them keep it. That's something they built — respect it.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'respect', 'autonomy'],
  },
  {
    id: 'cf_reunification_004',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "Homecoming has hard days. A hard day after coming home is not a sign that things are broken. It's a sign that real life started.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'normalization', 'honesty'],
  },
  {
    id: 'cf_reunification_005',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "{child_name} may push back. They may test you. That's not about whether you've changed — it's about whether your change holds when they push.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'testing', 'consistency'],
  },
  {
    id: 'cf_reunification_006',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "If {child_name} wants to breathe alone, that's not rejection. That's self-regulation they built — possibly because of what you started.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'autonomy', 'self_regulation'],
  },
  {
    id: 'cf_reunification_007',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "Repair after reunion is still repair. The skills haven't changed. See what happened. Own your part. Show up differently.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'repair', 'accountability'],
  },
  {
    id: 'cf_reunification_008',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "{parent_name}, showing up at home is different from showing up in here. The practice is the same — the setting isn't. Be patient with the adjustment.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'patience', 'adjustment'],
  },
  {
    id: 'cf_reunification_009',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "Coming home can feel like relief and pressure at the same time. Both are real. Name them separately so neither one runs the show.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'naming', 'complexity'],
  },
  {
    id: 'cf_reunification_010',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "{child_name} may not want your closeness right away. That's not about you — it's about their timeline. Your calm says 'I'm here when you're ready.'",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'patience', 'co_regulation'],
  },
  {
    id: 'cf_reunification_011',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "The first week home is not a test. It's a beginning. Beginnings are messy — and that's fine.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'normalization', 'patience'],
  },
  {
    id: 'cf_reunification_012',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "If a conversation with {child_name} goes sideways, you know what to do. Breathe. Regulate. Come back. The tools work outside these walls too.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'repair', 'self_regulation'],
  },
  {
    id: 'cf_reunification_013',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "You imagined this day many times. The real version will look different from every one of those. Let the real version be enough.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'acceptance', 'expectations'],
  },
  {
    id: 'cf_reunification_014',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "{parent_name}, if you feel overwhelmed being home, say it out loud — at least to yourself. 'I feel overwhelmed' is information, not weakness.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'naming', 'honesty'],
  },
  {
    id: 'cf_reunification_015',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "Your child's bedtime routine, their food preferences, their inside jokes with the caregiver — those aren't threats to your role. They're signs of a life that kept going.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'acceptance', 'parenting'],
  },
  {
    id: 'cf_reunification_016',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "Making up for lost time isn't the work. Making the most of present time — that's the work.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'presence', 'acceptance'],
  },
  {
    id: 'cf_reunification_017',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "{child_name} may bring up things from the past. If they do, breathe before you respond. Their memory is their truth — and it deserves space.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'repair', 'listening'],
  },
  {
    id: 'cf_reunification_018',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "Home will feel unfamiliar in some ways. That doesn't mean you don't belong there. It means you've been away, and that's a fact, not a judgment.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'normalization', 'acceptance'],
  },
  {
    id: 'cf_reunification_019',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "If {child_name} acts out in the first few weeks, remember: big feelings come from big transitions. Your steady presence is the answer, not a lecture.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'co_regulation', 'parenting'],
  },
  {
    id: 'cf_reunification_020',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "You might feel guilty about feeling happy. Or feel sad in a moment that's supposed to be joyful. Feelings don't follow scripts, and that's okay.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'naming', 'complexity'],
  },
  {
    id: 'cf_reunification_021',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "{parent_name}, ordinary days at home — dishes, homework, quiet evenings — are where the real reconnection happens. Not the big moments.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'presence', 'everyday'],
  },
  {
    id: 'cf_reunification_022',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "Trust gets rebuilt in small moments, not grand gestures. A kept word. A calm response. A consistent bedtime. These are the materials.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'trust', 'consistency'],
  },
  {
    id: 'cf_reunification_023',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "{child_name} learned to soothe themselves while you were away. That's not a replacement for you — it's a strength they built. Honor it.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'autonomy', 'respect'],
  },
  {
    id: 'cf_reunification_024',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "Let go of the idea that things return to how they were. You're building something new — and new can be good without being the same.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'acceptance', 'growth'],
  },
  {
    id: 'cf_reunification_025',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "If {child_name} says 'I don't know you anymore,' that's honest. It's painful, but honest. Meet it with breath, not defense.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'honesty', 'vulnerability'],
  },
  {
    id: 'cf_reunification_026',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "The work you did inside these walls doesn't disappear when you walk out. It walks with you.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'identity', 'growth'],
  },
  {
    id: 'cf_reunification_027',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "Family meals might feel awkward. Silences might feel heavy. That's the real texture of reunion — not a movie scene, but a real room with real people.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'normalization', 'honesty'],
  },
  {
    id: 'cf_reunification_028',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "{parent_name}, if you slip — raise your voice, shut down, go quiet when you mean to speak — you already know the next step. Come back. That's the skill.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'repair', 'self_compassion'],
  },
  {
    id: 'cf_reunification_029',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "{child_name} has changed. You've changed. The relationship between you is finding its new shape. Let it take the time it takes.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'patience', 'acceptance'],
  },
  {
    id: 'cf_reunification_030',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "Loneliness can happen even when you're surrounded by family. If it shows up, name it. It doesn't mean you made the wrong choice — it means transition is real.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'naming', 'normalization'],
  },
  {
    id: 'cf_reunification_031',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "You may feel pressure to be the perfect parent now that you're home. Release that. You practiced being present, not perfect.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'self_compassion', 'presence'],
  },
  {
    id: 'cf_reunification_032',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "When {child_name} is upset and you stay calm, they may not thank you. They may not even notice. But something inside them registers: 'This person is steady.'",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'co_regulation', 'patience'],
  },
  {
    id: 'cf_reunification_033',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "There will be moments at home when old patterns knock on the door. You've practiced not answering. Keep practicing.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'self_regulation', 'patterns'],
  },
  {
    id: 'cf_reunification_034',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "Other people may have opinions about your homecoming. Their expectations are theirs. Your path is yours.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'boundaries', 'acceptance'],
  },
  {
    id: 'cf_reunification_035',
    domain: 'emotional_vocabulary',
    min_gate: 'gate_4',
    template: "{parent_name}, it's okay to feel grief even in the middle of a good thing. Coming home surfaces what was missed. Let yourself feel it.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'grief', 'acceptance'],
  },
  {
    id: 'cf_reunification_036',
    domain: 'co_regulation',
    min_gate: 'gate_4',
    template: "If {child_name} doesn't want to hear about your breathing practice, that's okay. You don't teach regulation by talking about it. You teach it by living it.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'modeling', 'respect'],
  },
  {
    id: 'cf_reunification_037',
    domain: 'showing_up',
    min_gate: 'gate_4',
    template: "Showing up at home means showing up to the boring parts too. The school run, the dishes, the bedtime stories. That's where consistency lives.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'consistency', 'everyday'],
  },
  {
    id: 'cf_reunification_038',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "If {child_name} is cold or distant, it doesn't erase everything you've built. It means they're processing on their own schedule. Keep your door open.",
    references_child: true,
    post_release: true,
    tags: ['reunification', 'patience', 'repair'],
  },
  {
    id: 'cf_reunification_039',
    domain: 'letting_go',
    min_gate: 'gate_4',
    template: "{parent_name}, you can't fast-forward reconnection. The same patience you practiced in breathing — apply it to your days at home.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'patience', 'presence'],
  },
  {
    id: 'cf_reunification_040',
    domain: 'repair',
    min_gate: 'gate_4',
    template: "The hardest and most beautiful thing about being home is that it's real. Real is messy, slow, unscripted, and worth it.",
    references_child: false,
    post_release: true,
    tags: ['reunification', 'honesty', 'acceptance'],
  },
];

// ---------------------------------------------------------------------------
// Helper: return entries eligible for a given gate (cumulative) and release status
// ---------------------------------------------------------------------------
function getEligibleEntries(gate, postRelease = false) {
  const GATE_ORDER = ['gate_1', 'gate_2', 'gate_3', 'gate_4'];
  const gateIdx = GATE_ORDER.indexOf(gate);
  return COACHING_FIRMWARE_LIBRARY.filter(e => {
    const entryIdx = GATE_ORDER.indexOf(e.min_gate);
    if (entryIdx > gateIdx) return false;
    if (e.post_release && !postRelease) return false;
    return true;
  });
}

// ---------------------------------------------------------------------------
// Helper: replace placeholders in a coaching template
// ---------------------------------------------------------------------------
function applyCoachingTemplate(template, vars) {
  let result = template;
  result = result.replace(/\{parent_name\}/g, vars.parent_name || 'You');
  result = result.replace(/\{child_name\}/g, vars.child_name || 'your child');
  result = result.replace(/\{breath_count\}/g, vars.breath_count || 'those');
  result = result.replace(/\{session_number\}/g, vars.session_number || '');
  return result;
}

module.exports = { COACHING_FIRMWARE_LIBRARY, getEligibleEntries, applyCoachingTemplate };
